/* ============================================================
   ArqFlow — Module Icon Map (UI layer)
   ------------------------------------------------------------
   Maps the string `icon` keys used in the (pure-data) module
   registry to concrete lucide-react components. Kept separate
   from registry.ts so the registry stays React-free and safely
   importable from server code, API routes, and n8n builders.
   ============================================================ */

import {
  LayoutDashboard,
  MessageSquare,
  Users,
  BarChart3,
  BookOpen,
  Send,
  Phone,
  Bot,
  Receipt,
  Crown,
  FolderOpen,
  Settings,
  ShoppingCart,
  Package,
  Wrench,
  Tag,
  Boxes,
  Truck,
  Percent,
  Ticket,
  CalendarDays,
  Stethoscope,
  HeartPulse,
  ClipboardPlus,
  ClipboardList,
  ClipboardCheck,
  Clock,
  CalendarCheck,
  BedDouble,
  DoorOpen,
  CreditCard,
  Dumbbell,
  UserCog,
  Building2,
  MapPin,
  GraduationCap,
  Scale,
  Briefcase,
  FileText,
  Car,
  UtensilsCrossed,
  ShoppingBag,
  Store,
  Hospital,
  Pill,
  Hotel,
  Scissors,
  Sparkles,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  LayoutDashboard,
  MessageSquare,
  Users,
  BarChart3,
  BookOpen,
  Send,
  Phone,
  Bot,
  Receipt,
  Crown,
  FolderOpen,
  Settings,
  ShoppingCart,
  Package,
  Wrench,
  Tag,
  Boxes,
  Truck,
  Percent,
  Ticket,
  CalendarDays,
  Stethoscope,
  HeartPulse,
  ClipboardPlus,
  ClipboardList,
  ClipboardCheck,
  Clock,
  CalendarCheck,
  BedDouble,
  DoorOpen,
  CreditCard,
  Dumbbell,
  UserCog,
  Building2,
  MapPin,
  GraduationCap,
  Scale,
  Briefcase,
  FileText,
  Car,
  UtensilsCrossed,
  ShoppingBag,
  Store,
  Hospital,
  Pill,
  Hotel,
  Scissors,
  Sparkles,
};

/** Resolve an icon key to a lucide component, with a safe fallback. */
export function getIcon(key: string): LucideIcon {
  return ICONS[key] ?? Sparkles;
}
